[extend]
useDefault = true

[[rules]]
description = "Hardcoded Vulnmap internal credentials"
id = "hardcoded vulnmap internal credentials"
regex = '''vulnmap(-[a-zA-Z]+)+:[a-zA-Z0-9]+'''

[allowlist]
description = "global allow list"
paths = [
  '''.bin''',
  'test/jwt/jwt_private_key.pem'
]
